include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = DailyPaperWeeApp
DailyPaperWeeApp_FILES = $(wildcard *.x) $(wildcard *.m)
DailyPaperWeeApp_FRAMEWORKS = UIKit CoreGraphics
DailyPaperWeeApp_PRIVATE_FRAMEWORKS = SpringBoardUIServices
DailyPaperWeeApp_INSTALL_PATH = /System/Library/WeeAppPlugins

include $(THEOS_MAKE_PATH)/bundle.mk
