include theos/makefiles/common.mk

BUNDLE_NAME = DailyPaper
DailyPaper_FILES = $(wildcard *.x) $(wildcard *.m)
DailyPaper_FRAMEWORKS = UIKit CoreGraphics
DailyPaper_PRIVATE_FRAMEWORKS = SpringBoardUIServices
DailyPaper_INSTALL_PATH = /System/Library/WeeAppPlugins

include $(THEOS_MAKE_PATH)/bundle.mk
